// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeV4tbKH0LwdwUqxJvNNIrCPMPnHccpww',
    appId: '1:18810982783:web:b457180b8d6724c6ef4a4a',
    messagingSenderId: '18810982783',
    projectId: 'alan-tune',
    authDomain: 'alan-tune.firebaseapp.com',
    storageBucket: 'alan-tune.appspot.com',
    measurementId: 'G-C84BVR5HPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAImzbuEiNk41F-Jqxz3JwmMHPfiRF3FGo',
    appId: '1:18810982783:android:925f38f68c233591ef4a4a',
    messagingSenderId: '18810982783',
    projectId: 'alan-tune',
    storageBucket: 'alan-tune.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEKN2l8tc6bUse7w7D02bik3W76MiAVLs',
    appId: '1:18810982783:ios:92fc42b6a83fe1f3ef4a4a',
    messagingSenderId: '18810982783',
    projectId: 'alan-tune',
    storageBucket: 'alan-tune.appspot.com',
    iosClientId: '18810982783-seoknbagvusrdtd73d21qi3470ehlrsd.apps.googleusercontent.com',
    iosBundleId: 'com.example.alanTune',
  );

}